#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument. Requirements:
# - Accepts a string as an argument
# - Displays a usage message if no argument is provided
# - Pings the IP address five times

if [ "$#" -eq 0 ]; then
   echo 'Usage: script_name {IP_ADDRESS}'
else
    ping -c 5 "$1"
fi

